platform :ios, '10.0'

require_relative '../node_modules/@unimodules/core/podfile-macro'

# don't just copy and paste this, notice that the target names should align with what is already in your Podfile
target 'Snap' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
    'RCTImage',
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'EXCamera', path: '../node_modules/expo-camera/ios'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'react-native-video', :path => '../node_modules/react-native-video'
  
  use_unimodules!

  target 'SnapTests' do
    inherit! :search_paths
  end
end